version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "poetry run python manage.py migrate --skip-checks &&
      poetry run python manage.py collectstatic --no-input &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lasfera"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
