version: "3.9"
services:
  app:
    build: .
    image: "rrchnm/lasfera"
    container_name: "lasfera-app"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=thisisnotasecretkey
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=lasfera
      - DB_USER=lasfera
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        poetry run python manage.py tailwind install --no-input &&
        poetry run python manage.py tailwind build --no-input &&
        poetry run python manage.py collectstatic --no-input &&
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
  db:
    image: postgres:16
    container_name: "lasfera-db"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lasfera
      - POSTGRES_USER=lasfera
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lasfera"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
