# Generated by Django 5.1.7 on 2025-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0116_alter_linecode_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationalias",
            name="show_on_page",
            field=models.BooleanField(default=False),
        ),
    ]
